language: php

dist: xenial

php:
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.3
      env: PHPCS=1 DEFAULT=0

    - php: 7.3
      env: PHPSTAN=1 DEFAULT=0

    - php: 7.3
      env: COVERAGE=1 DEFAULT=0 DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test?init[]=SET sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"'

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $DEFAULT = 1 ]]; then composer test; fi
  - if [[ $DEFAULT = 1 ]]; then composer stan-integration; fi
  - if [[ $COVERAGE = 1 ]]; then composer coverage-test; fi
  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then composer stan; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
