name: CI

on:
  push:
    branches:
      - 'master'
      - '3.next-cake5'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  testsuite-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']
        dependencies: ['highest']
        include:
          - php-version: '8.1'
            dependencies: 'lowest'
          - php-version: '8.2'
            dependencies: 'highest'
          - php-version: '8.3'
            dependencies: 'highest'

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          ini-values: zend.assertions=1
          tools: cs2pr

      - name: Composer install
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer-options }}

      - name: Run PHPUnit
        run: vendor/bin/phpunit

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl
          coverage: none
          tools: phive, cs2pr

      - name: Composer Install
        uses: ramsey/composer-install@v2

      - name: Run phpcs
        run: vendor/bin/phpcs --report=checkstyle src/ tests/ | cs2pr

      - name: Run phpstan
        if: always()
        run: vendor/bin/phpstan analyse --debug --error-format=github src/

      - name: Run phpstan integration test app
        if: always()
        run: vendor/bin/phpstan analyse --debug --error-format=github tests/test_app/

      - name: Run phpstan integration test plugin
        if: always()
        run: vendor/bin/phpstan analyse --debug --error-format=github tests/test_plugin/
